### ISSUE TITLE
Refactor Profile

### ISSUE THREAD

**Issue by martialblog** [vision-it/vision-mysql#7]
The profile has grown over time and could benefit from a refactor.

**Comment by martialblog** [comment]
Started here https://github.com/vision-it/vision-mysql/tree/refactor

**Comment by jacksgt** [comment]
Let's not do to many things in one commit, please.

While we're at it, is the [puppet-staging](https://github.com/voxpupuli/puppet-staging) module still needed?
https://github.com/vision-it/vision-mysql/blob/322942604ede3804fd7cabc8eb23c9b2de34de00/.fixtures.yml#L10

**Comment by martialblog** [comment]
I updated to puppet-mysql 7.0, so no more staging :tada:

**Comment by jacksgt** [comment]
Why not update to 8.0.0?
https://github.com/puppetlabs/puppetlabs-mysql/releases

**Comment by martialblog** [comment]
Working on it... :keyboard:

**Comment by jacksgt** [comment]
I see, I was just wondering wether there was a specific reason (incompatibility etc.)

**Comment by martialblog** [comment]
Hopefully not

**Comment by martialblog** [comment]
@jacksgt Check it out: https://github.com/vision-it/vision-mysql/tree/issue-7
